### PR TITLE
Tmpl nl mobility

### PR DESCRIPTION
**Pull request by bosd**
With these templates you will be able to process 95% of dutch fuel station receipts.
Additionnaly:
- ANWB Road assistance
- ipparking
- ns rail invoices
- parkmobile parking app

### CODE REVIEW

**Comment by rmilecki** [comment]
What's the point of that commented out code repeated in so many templates?
```
# below code is wrong pump name and with product field
#    line: .(?P<product>\w*).?\s+.\s.\s+\d+.\d{0,2}\n.?\s+.(?P<name>POMP.*) (?P<qty>\d+.\d{2})\s. .\s+€ (?P<price_unit>\d.\d{3})
# Above one modified for file without line breaks
#    line: .(?P<product>\w*).?\s+.\s.\s+\d+.\d{0,2}.*.?\s+.(?P<name>POMP.*) (?P<qty>\d+.\d{2})\s. .\s+€ (?P<price_unit>\d.\d{3})
# same as above optimized for (non optimized string)
#    line: .(?P<product>(\w+(?:\S|[.]\w\w+|\n)*)).?\s+.\s.\s+\d+.\d{0,2}.*.?\s+.(?P<name>POMP.*) (?P<qty>\d+.\d{2})\s. .\s+€ (?P<price_unit>\d.\d{3})
```

**Comment by bosd** [comment]
> What's the point of that commented out code repeated in so many templates?

I'll have a look at it again.
I've started making these templates a while ago. Back then I assumed that 378 got merged.
But that PR did not get merged. There have been some alternative pr's since that one.

Need to look at it again, if the alternative pr's are now providing the same functionality.

**Comment by bosd** [comment]
Interesting to add..
Some of these templates are for recognizing tickets from POS systems.
That is a particular challenging task. Because the receipts need to be scanned and processed by tesseract ocr.
I am able to achieve some impressive results. Really usable. So I am willing to provide these as an example here.
However, the results are still inconsistent.

By that I mean, with the same input file, same processing command, the result can be different.
Therefore not suitable for using them as an exact unit test match.


Currently tesseract is untested see #109 .
Since then tesseract has improved a lot. It is usable, we can try to make a unittest for it.
Maybe under ideal conditions we could get 100% repeatative results..
Alhough I am not sure.
Is there a way to add a non blocking test.?
So when it fails, it would not block the whole github actions cycle?

**Comment by bosd** [comment]
I appoligize for all the activity in this PR.
I tried to fix the future warning. But it was not introduced by these commits.
Eventually found it, and fix is in #516 

This PR has been sitting here for quite some while.
It is one of the items I want to get off my task list.
So, Will make this ready to be merged.

If one of these templates needs update. I will do that in micro commits / PR's.
Going to sqaush all the commits here. And merge this one.

**Pull request merged**
