### PR TITLE
Adjusting lines plugin to only look for line between first and last

### PR DESCRIPTION
**Pull request by RossK1**
Currently the behaviour of the lines plugin seems a little counter intuitive in that it will record "line" even before a "first_line" has been found.

With these changes, the plugin will begin by finding a "first_line". When that matches, it will look for "line", appending matches to the first_line until it either finds "last_line" or another "first_line".

This allows for more logical structuring of text searches and control of where and what data is extracted.

### CODE REVIEW

**Comment by m3nu** [comment]
@hbrunn , what do you think of this addition?

**Comment by RossK1** [comment]
@m3nu and @hbrunn , any update on this?

**Comment by hbrunn** [comment]
I abandoned this project a while ago and work on an ML-based approach (tensorflow) with OCR (tesseract). In a while I'll publish a container that you can pass pdfs+their coding for training and afterwards send it a pdf and get back some json with the coding.

**Comment by RossK1** [comment]
@m3nu . Any update on testing and approval for this change?

Thanks :)

**Comment by m3nu** [comment]
If you fix the confusing IF-statement I marked, we can merge this.

**Comment by RossK1** [comment]
@m3nu Please have a look at the latest commit. I added commentary throughout the new code to explain the logic behind it, together with an explanation at the top for those reviewing or maintaining in the future.
The parsing of rows was also repeated in the code, so I moved that into a separate function while I was at it, just to clean it up a little :)
Everything is Black formatted and passing tests, so should be good to go.
Appreciate your time!

**Comment by m3nu** [comment]
You don't want a test for your changes? Fine with me, but it may break if someone makes a change in the future.

**Comment by RossK1** [comment]
Yeah, let me add a quick test to make sure it works properly and prevent future breakage :)

**Comment by RossK1** [comment]
@m3nu Tests added together some extra to the readme and an additional feature of skip_lines. Basically allows something between the first_line and last_line to be skipped if not desired to be captured.

**Review by m3nu — APPROVED** [review]

**Comment by vzeazy** [comment]
> I abandoned this project a while ago and work on an ML-based approach (tensorflow) with OCR (tesseract). In a while I'll publish a container that you can pass pdfs+their coding for training and afterwards send it a pdf and get back some json with the coding.

Just starting with this library and definitely though tensorflow would be perfect for something like this. Just wondering if you made any progress? Can't seem to find any associated repos.

**Pull request merged**
