### PR TITLE
shift ci tests from python 3.6-3.9 to 3.8-3.10 

### PR DESCRIPTION
**Pull request by bosd**
Python 3.6 is deprecated.
3.10 installations are becoming more common.

Version shift the CI tests to keep track of supported python versions

### CODE REVIEW

**Review by m3nu — APPROVED** [review]

**Comment by bosd** [comment]
Thanks for the merge! :sunglasses: 
Kindly look at my other PR's, to merge those as they have a bit higher priority :innocent:

**Comment by m3nu** [comment]
I've added you as maintainer, so you can merge directly. This project isn't a priority for me recently, so happy if someone else takes care for a while.

**Comment by bosd** [comment]
@m3nu  
Thanks! I'm glad to be added as a maintainer.

With the merge of PR's the current open PR's can't be merged.
As they are still looking for the python3.6 tests.

The tests are managed differently from the rules to be able to merge PR's.
Can you also change the requirements from python 3.6 to python 3.10.6?

see:
https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/managing-a-branch-protection-rule

**Comment by m3nu** [comment]
Yes, already changed the branch protection rules.

**Comment by bosd** [comment]
Great! Oud messages/actions crosser each other

**Pull request merged**
