### PR TITLE
[WIP] Some Belgian suppliers

### PR DESCRIPTION
**Pull request by rubdos**
Please refrain from merging for now. We are adding our Belgian suppliers and would love them to be upstream. Currently still a tid bug-prone, we're fixing.

- [ ] Alternate business. Might be useful in `.de` region too.
  - [x] Single serial number
  - [ ] Multiple serial number
  - [ ] VAT table parsing
- [ ] Copaco. Might be useful in `.nl` region too.
  - [ ] Multi page invoice test
- [ ] edpnet. Local ISP

### CODE REVIEW

**Comment by m3nu** [comment]
Is this still work in progress?

**Comment by rubdos** [comment]
Yes... I don't have a ton of time to work on it, but I'm still with the intention to get these things pretty far. When I get the bugs out of be.alternate, I'll let you know for a first merge. That okay?

**Comment by m3nu** [comment]
Great. Every addition is appreciated.

**Comment by rmilecki** [comment]
Please reopen if you decide to get back working on this :)

**Pull request closed without merging**
