### PR TITLE
Adding regex keywords and exclude keywords

### PR DESCRIPTION
**Pull request by RossK1**
Hi,

Love the package, so would like to contribute a few little modifications :)

I have changed the keyword search to regex search rather than substring find. This allows regex patterns to be used as keywords, allowing even more flexibility should one desire.
I also added the optional exclude_keywords, again accepting regex patterns, to exclude a template if any are found.

Tutorial and readme were updated to reference the new functionality.

This is my first contribution to an open source project, so please let me know if there is anything I need to do or add.

Thanks!

### CODE REVIEW

**Comment by RossK1** [comment]
Hmmm. Not sure why the lint check is failing. Linting in VS code all seems happy.

**Comment by m3nu** [comment]
Hi and thanks for the contributions!

We lint with Flake8. It will print the detailed issues it sees in the Github Action log:

```
./src/invoice2data/extract/invoice_template.py:97:1: W293 blank line contains whitespace
./src/invoice2data/extract/invoice_template.py:100:1: W293 blank line contains whitespace
./src/invoice2data/extract/invoice_template.py:111:121: E501 line too long (141 > 120 characters)
./src/invoice2data/extract/loader.py:101:1: W293 blank line contains whitespace
```

**Comment by RossK1** [comment]
Yay, looks like the tests liked the edits!
(ignore the close and re-open, I mashed the buttons on my phone 🙄 )
Let me know what you think and if there's anything else I need to do to get these updates merged in 😃

**Comment by erkin98** [comment]
> Yay, looks like the tests liked the edits!
> (ignore the close and re-open, I mashed the buttons on my phone 🙄 )
> Let me know what you think and if there's anything else I need to do to get these updates merged in 😃

bro how to use your modifications?

**Comment by RossK1** [comment]
> bro how to use your modifications?

Until @m3nu is able to review and merge, you should be able to clone my fork and use that in your code.

**Review by m3nu — APPROVED** [review]

**Comment by m3nu** [comment]
Merged. Thanks for the contribution!

**Comment by erkin98** [comment]
> > bro how to use your modifications?
> 
> Until @m3nu is able to review and merge, you should be able to clone my fork and use that in your code.

what exactly do this exclude keywords?

**Comment by RossK1** [comment]
> what exactly do this exclude keywords?

It's been merged in now :) So you should just be able to pip install or update and get the new functionality.

As for use, in your template you can now specify not only keywords, but also exclude_keywords and both accept regex patterns. For example:
```
keywords:
    - 'Company\s+(US|UK)'
    - 'finance\@company\.com'
exclude_keywords:
    - 'Company\s+FR'
    - 'compliance\@company\.com'
```
That will match any text where it finds "Company US" OR "Company UK" AND "finance@company.com" but even if those keywords are found, it will reject it if it finds "Company FR" OR "compliance@company.com".
This gives you a bit more flexibility for templates to match the desired pdf.

**Comment by m3nu** [comment]
There is no release on PyPi yet, but you can install from the master branch using Pip. Something like

`$ pip install git+https://github.com/...`

**Pull request merged**
