### PR TITLE
Fix issue #316: Add support for all template variables in filename.

### PR DESCRIPTION
**Pull request by sandervd**
First of all, thank you for this project!

This PR adds support for any template variable to be used in the filename as requested in #316.

### CODE REVIEW

**Comment by bosd** [comment]
@m3nu Can you trigger tests?

**Comment by m3nu** [comment]
This is not about permissions. Just stuck https://stackoverflow.com/a/58190576/3983708

**Comment by m3nu** [comment]
This one seems genuinely stuck. No button to approve.

**Comment by bosd** [comment]
@sandervd Can you force push to re-trigger tests?

**Comment by sandervd** [comment]
@bosd Let's see how it goes...

**Comment by bosd** [comment]
Closing this one as it is superseded by #403

**Pull request closed without merging**
